######   LOCAL   ######

# Sync changes to REMOTE (will trigger image rebuild on REMOTE):
# rsync -e ssh -aF --delete . dots:/home/opc/dots/

######   REMOTE   ######

# ONLY RUN ON FIRST DEPLOYMENT !!!
# Generate certificates:
# docker compose -f /home/opc/dots/docker-compose.yml run --rm --entrypoint \
#   "certbot certonly --webroot -w /var/www -d condots.duckdns.org" \
#   certbot

# Trigger rebuild on changes (run once):
# nohup docker compose -f /home/opc/dots/docker-compose.yml watch > /tmp/docker-compose.log 2>&1 &

# To stop docker compose:
# docker compose -f /home/opc/dots/docker-compose.yml down && \
#   pkill -f 'docker compose -f /home/opc/dots/docker-compose.yml watch'

services:
  dots:
    image: dots
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '80:80'
      - '443:443'
    user: root
    volumes:
      - webroot:/var/www:rw
      - ./certs:/etc/letsencrypt:rw
      - ./entrypoint.sh:/entrypoint.sh
    entrypoint: ['/bin/sh', '/entrypoint.sh']
    depends_on:
      - certbot
    develop:
      watch:
        - action: rebuild
          path: .
          target: build

  certbot:
    image: certbot/certbot
    volumes:
      - certs-lib:/var/lib/letsencrypt
      - webroot:/var/www
      - ./certs:/etc/letsencrypt
      - ./logs:/var/log/letsencrypt
      - ./renewal-script.sh:/etc/renewal-script.sh
    entrypoint: /bin/sh -c '/etc/renewal-script.sh'

volumes:
  certs-lib:
  webroot:
