# Start webserver on vm as root (run only once): docker compose -f /home/opc/dots/docker-compose.yml watch &
# Sync local changes (image will be rebuilt): rsync -e ssh -aF --delete . dots:/home/opc/dots/

# ONLY ON FIRST DEPLOYMENT !!!
# Generate the initial certificates:
# docker compose -f dots/docker-compose.yml run --rm --entrypoint "certbot certonly --webroot -w /usr/share/nginx/html -d condots.duckdns.org" certbot

services:
  dots:
    image: dots:latest
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - certs:/etc/letsencrypt
    develop:
      watch:
        - action: rebuild
          path: .

  certbot:
    image: certbot/certbot
    volumes:
      - certs:/etc/letsencrypt
      - certs-data:/data/letsencrypt
      - letsencrypt-renewal:/etc/letsencrypt-renewal
      - ./renewal-script.sh:/etc/renewal-script.sh
    entrypoint: /bin/sh -c '/etc/renewal-script.sh'

volumes:
  certs:
  certs-data:
  letsencrypt-renewal:
